version: '3.9'

networks:
  proxynet:
    driver: bridge

services:
    
  api:
    build: 
      context: ../../
      dockerfile: Prepps.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "../Prepps/Infrastructure/Credentials/prepps-50cf66a9a284.json"
    networks:
      - proxynet
 
  frontend: 
    build:
     context: ../../Prepps.Svelte
     dockerfile: Dockerfile
    ports:
       - "3000:80"
    environment:
      api: 'http://localhost:5000'
    networks:
       - proxynet

volumes:
  db:
    driver: local